import { TOKEN_EXPIRES_IN } from './constants';

import {
  BAD_REQUEST,
  BALANCE_AVAILABLE_IS_NOT_ENOUGH,
  BLOCK_TRANSACTION_IS_NOT_OPEN,
  DEPOSIT_RANGE_VALID_IS,
  IS_LOGGED_IN,
  MINIMUM_QUANTITY_IS,
  NOT_ENOUGH_MONEY,
  NOT_FOUND,
  NOT_FOUND_POSITION,
  TRADING_SESSION_IS_NOT_OPEN,
  UNAUTHORIZED,
  WITHDRAWAL_RANGE_VALIS_IS,
} from './error-message';

export const MESSAGE = {
  TRADING_SESSION_IS_NOT_OPEN,
  BLOCK_TRANSACTION_IS_NOT_OPEN,
  MINIMUM_QUANTITY_IS,
  BALANCE_AVAILABLE_IS_NOT_ENOUGH,
  NOT_FOUND,
  BAD_REQUEST,
  NOT_FOUND_POSITION,
  IS_LOGGED_IN,
  UNAUTHORIZED,
  DEPOSIT_RANGE_VALID_IS,
  WITHDRAWAL_RANGE_VALIS_IS,
  NOT_ENOUGH_MONEY,
};

export { TOKEN_EXPIRES_IN };
